### ISSUE TITLE
Extract TRANSITION_DURATION from CSS using getComputedStyle()

### ISSUE THREAD

**Issue by afshin** [phosphorjs/phosphor#130]
If possible, use `getComputedStyle()` to parse the CSS transition value instead of needing the TS and CSS files to be in sync:
```typescript
/**
 * The tab transition duration.
 */
const TRANSITION_DURATION = 150;  // Keep in sync with CSS.
```
from [ui/tabbar.ts](https://github.com/phosphorjs/phosphor/blob/42d1c2a646ac327da8b98f4a129a7d8947679ea6/src/ui/tabbar.ts#L116-L119)
```css
.p-TabBar.p-mod-horizontal.p-mod-dragging .p-TabBar-tab {
  left: 0;
  transition: left 150ms ease; /* keep in sync with JS */
}


.p-TabBar.p-mod-vertical.p-mod-dragging .p-TabBar-tab {
  top: 0;
  transition: top 150ms ease; /* keep in sync with JS */
}
```
from [styles/base.css](https://github.com/phosphorjs/phosphor/blob/42d1c2a646ac327da8b98f4a129a7d8947679ea6/styles/base.css#L291-L300)
