### ISSUE TITLE
CommandPalette - disable query/search functionality

### ISSUE THREAD

**Issue by birdsarah** [phosphorjs/phosphor#257]
Whilst it's a great feature, it'd be nice to have a flag to be able to turn it off when you don't want it.

**Comment by afshin** [comment]
You could write some CSS to hide the search functionality, effectively disabling it at runtime:
```css
.p-CommandPalette-search {
  display: none;
}
```
